// export * from "./Advantages"
// export { default as Advantages } from "./Advantages"
// export { default as AdvantageCard } from "./Advantages"
export { default as BatteriesSection } from "./BatteriesSection"
export { default as BikeOptions } from "./BikeOptions"
export { default as ContactUsForm} from "./ContactUsForm"
export { default as  FQA } from "./FQA"
export { default as GeneralInfo} from "./GeneralInfo"
export { default as MainSection } from "./MainSection"
export { default as NewUs } from "./NewUs"
export { default as Performance } from "./Performance"
export { default as Plans } from "./Plans"
